# Site
repository: sudhanshublah/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudhanshu Kumar
title: DevOps | MLOps Engineer
email: sudhanshuk1219@gmail.com
website: www.github.com/sudhanshublah

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: sudhanshublah
linkedin_username: sudhanshu-kumar-673034181

# About Section
about_profile_image: images/profile.JPG
about_content: | 
  Hi, I'm Sudhanshu Kumar, a DevOps and MLOps Engineer with experience in designing, deploying, and optimizing cloud-native and AI-driven solutions. I specialize in cloud platforms like AWS and GCP, as well as tools and technologies such as Kubernetes, Terraform, and FastAPI. My passion lies in integrating DevOps best practices with cutting-edge Generative AI models to enable scalable, high-performance systems.

  I am skilled in:  
  - **DevOps Tools**: Docker, Kubernetes, Terraform, CI/CD pipelines (Jenkins, GitHub Actions)  
  - **Cloud Platforms**: AWS, GCP, and Vertex AI  
  - **MLOps**: Torchserve, Triton Inference Server, Ray Serve, TensorRT  
  - **Compliance**: SOC 2  
  - **Backup Solutions**: Veeam, BackupCARoleService  

  I thrive on solving complex technical problems and continuously learning to stay ahead in this fast-paced industry.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Generative AI Deployment on Vertex AI
        link: https://github.com/sudhanshublah/vertex-ai-deployment
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/sudhanshublah/vertex-ai-deployment
        quote: >
          Enabled scalable and cost-efficient Generative AI solutions on Vertex AI with seamless API integrations.
        description: | 
          Built an infrastructure to deploy and scale Generative AI models using GCP Vertex AI. Optimized GPU utilization and integrated Triton Inference Server with TensorRT to enhance model performance. Managed API endpoints using FastAPI and implemented autoscaling using Kubernetes.  

      - layout: top-middle
        title: Security Group Management in AWS
        link: https://github.com/sudhanshublah/aws-sg-management
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/sudhanshublah/aws-sg-management
        quote: >
          Automated the identification and backup of unused AWS security groups across multiple accounts.
        description: | 
          Designed a Python script to list and back up unused security groups in AWS. Integrated the solution with S3 for configuration backups, ensuring easy recovery without immediate deletion. Reduced manual intervention and improved cloud resource hygiene.  

      - layout: top-middle
        title: Stable Diffusion Model Deployment
        link: https://github.com/sudhanshublah/stable-diffusion-deployment
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/sudhanshublah/stable-diffusion-deployment
        quote: >
          Empowered creative teams with an efficient deployment of Stable Diffusion models on Kubernetes clusters.
        description: | 
          Deployed a scalable Stable Diffusion model on GKE and standalone VMs. Configured API Gateways and ensured seamless scaling with Ray Serve. Integrated ML pipelines for model updates and optimized resource usage for high availability.  

  - title: Experience
    layout: list
    content:
      - layout: left
        title: DevOps Engineer
        link: https://imagine.io
        sub_title: Imagine.io, New Delhi
        caption: August 2023 - Present
        quote: >
          Building scalable and efficient infrastructure for Generative AI and cloud-native applications.
        description: | 
          - Deployed Generative AI models using Kubernetes, Vertex AI, and Triton Inference Server.  
          - Designed SOC 2 compliance strategies for security and reliability.  
          - Worked on API Gateway configurations and backup strategies for critical resources.  
          - Collaborated with cross-functional teams to utilize GCP credits efficiently.  

      - layout: left
        title: Cloud Engineer
        link: https://examplecompany.com
        sub_title: Example Company, Bangalore
        caption: May 2020 - August 2023
        quote: >
          Engineered cloud-based solutions and optimized CI/CD pipelines for seamless deployment.
        description: | 
          - Built Terraform scripts for infrastructure automation.  
          - Migrated on-prem applications to AWS and implemented disaster recovery strategies using Veeam.  
          - Improved container orchestration with Kubernetes and Helm.  
          - Automated compliance and audit processes to meet regulatory standards.  

  - title: Education
    layout: list
    content:
      - layout: left
        title: Delhi Technological University
        caption: 2015 - 2019
        sub_title: B.Tech Computer Engineering
        quote: >
          Acquired a strong foundation in software engineering and cloud technologies.
        description: | 
          Gained expertise in algorithms, data structures, and distributed systems. Participated in hackathons and led a team to build an award-winning project integrating IoT with AI for smart home systems.  

  - title: A Little More About Me
    layout: text
    content: | 
      Outside of work, I enjoy exploring new technologies and experimenting with Generative AI. My hobbies and interests include:  
      - Chess  
      - Photography  
      - Traveling to explore new cultures  
      - Rock climbing and fitness  

      I also find joy in mentoring young professionals and contributing to open-source projects.

# Footer
footer_show_references: true
# references_title: References available upon request.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
